# Generated by Django 5.2.15 on 2026-06-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pracdjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iprequestlog',
            old_name='ip_address',
            new_name='ip_addr',
        ),
    ]
