# Generated by Django 5.2.15 on 2026-06-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracdjango', '0002_rename_ip_address_iprequestlog_ip_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iprequestlog',
            old_name='ip_addr',
            new_name='ip_address',
        ),
        migrations.AddField(
            model_name='iprequestlog',
            name='request_count',
            field=models.IntegerField(default=1),
        ),
    ]
