# Generated by Django 5.2.15 on 2026-06-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('age', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
