# Generated by Django 5.2.15 on 2026-06-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learndjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(db_column='phone', default='', max_length=11),
        ),
    ]
