# Generated by Django 5.2.15 on 2026-06-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learndjango', '0003_course_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_nm', models.CharField(max_length=64)),
                ('c_name', models.CharField(max_length=64)),
            ],
        ),
    ]
